### ISSUE TITLE
1st test

### ISSUE THREAD

**Issue by MZorzy** [TrakHound/TrakHound-DataClient#1]
Hi Patrick
on client.config (not client.conf as in Readme.me) i set the okuma mtconnect stream online as :
cut
```
  <Devices>
    <Device deviceId="2cc32362-c3d4-48b7-b9f2-038bfb564e02" address="74.203.109.245" port="5000" deviceName="OKUMA.Lathe" interval="500" />
    <Device deviceId="41009954-1512-4679-a067-31df381f6c15" address="74.203.109.245" port="5001" deviceName="OKUMA.MachiningCenter" interval="500" />
  </Devices>
```
cut
set up a mySQL community on Win7, added trakhund user (as full admin) and DB, run "mysql-create-tables.sql" & "mysql-create-getinstance.sql" to populate table.

data from okuma is written on mySQL and at first look is all running, on DataServer consolle see "written to database successfull" and on DataClient "Sent successfully"
BUT after few times DataServer consolle start to print error on XML document (2, 2)
then Dataserver connection interrupt and restart as normal
![test1](https://cloud.githubusercontent.com/assets/1736388/24445280/a5b647b4-1469-11e7-8d8e-5e838ce706d7.png)

dataserver 1.2.3
dataclient 1.3.0

**Comment by PatrickRitchie** [comment]
It looks like you may have the incorrect Device Name for the Lathe at port 5001. The Okuma public agents should be:

http://74.203.109.245:5000/OKUMA.Lathe
http://74.203.109.245:5001/OKUMA.Lathe
http://74.203.109.245:5002/OKUMA.MachiningCenter
http://74.203.109.245:5003/OKUMA.Grinder

Having an incorrect DeviceName would result in an MTConnectError document instead of an MTConnectStreams document. I'm looking into why the Error document isn't handled better though.

**Comment by MZorzy** [comment]
thankyou, now WORK with "Device Name" on DataClient = "Device" from machine.
i though that it may be like a machine's nickname.

( i picked from
https://www.challenge.gov/files/2015/04/MTConnect-Challenge-Application-Development-Rules-16FEB2016.pdf )

**Comment by PatrickRitchie** [comment]
Glad to hear its working now!

Yeah the DeviceName is the actual MTConnect Device's name attribute and has to be specified since an Agent can have multiple Devices.
